

# netlify.toml

[build]
  base = "my-project"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Halaman utama menggunakan HTML statis
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

# Halaman tentang-saya menggunakan Next.js murni
[[redirects]]
  from = "/tentang-saya"
  to = "/.netlify/functions/next/tentang-saya"
  status = 200

# Semua halaman lainnya menggunakan Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next/:splat"
  status = 200

